services:
  - type: web
    name: versus-app-backend
    runtime: python3
    buildCommand: "./build.sh"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.10
      - key: DATABASE_URL
        fromDatabase:
          name: versus-app-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"

databases:
  - name: versus-app-db
    databaseName: versus_app
    user: versus_app_user
