# Generated by Django 4.2.23 on 2025-08-25 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile_coins_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título de la batalla', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descripción de la batalla')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(help_text='Cuándo termina la batalla')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duración en minutos')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('finished', 'Terminada'), ('cancelled', 'Cancelada')], default='active', max_length=10)),
                ('total_coins_a', models.PositiveIntegerField(default=0, help_text='Total de coins apostados al influencer A')),
                ('total_coins_b', models.PositiveIntegerField(default=0, help_text='Total de coins apostados al influencer B')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_created', to=settings.AUTH_USER_MODEL)),
                ('influencer_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_a', to=settings.AUTH_USER_MODEL)),
                ('influencer_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_b', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_influencer',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BattleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_profit', models.PositiveIntegerField(help_text='Coins para la plataforma')),
                ('winner_profit', models.PositiveIntegerField(help_text='Coins para el influencer ganador')),
                ('sorteo_profit', models.PositiveIntegerField(help_text='Coins para el sorteo')),
                ('commission_a', models.PositiveIntegerField(help_text='Comisión para influencer A')),
                ('commission_b', models.PositiveIntegerField(help_text='Comisión para influencer B')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('battle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='api.battle')),
                ('sorteo_winner', models.ForeignKey(blank=True, help_text='Ganador del sorteo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorteo_wins', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_won', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BattleBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('influencer_choice', models.CharField(choices=[('a', 'Influencer A'), ('b', 'Influencer B')], help_text='Influencer elegido', max_length=1)),
                ('coins_amount', models.PositiveIntegerField(help_text='Cantidad de coins apostados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='api.battle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_bets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'battle')},
            },
        ),
    ]
