# Generated by Django 4.2.23 on 2025-09-10 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_battle_userprofile_is_influencer_battleresult_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del sorteo', max_length=200)),
                ('description', models.TextField(help_text='Descripción del sorteo')),
                ('target_amount', models.PositiveIntegerField(help_text='Monto objetivo en coins')),
                ('current_amount', models.PositiveIntegerField(default=0, help_text='Monto actual recaudado')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('completed', 'Completado'), ('processed', 'Procesado')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='Cuándo se procesó el sorteo', null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raffles_created', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, help_text='Ganador del sorteo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raffles_won', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RaffleParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins_amount', models.PositiveIntegerField(help_text='Cantidad de coins participando')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='api.raffle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raffle_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'raffle')},
            },
        ),
    ]
