# Generated by Django 4.2.23 on 2025-09-17 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_raffle_raffleparticipation'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='referral_code_used',
            field=models.CharField(blank=True, help_text='Código de referido utilizado', max_length=6),
        ),
        migrations.AddField(
            model_name='transaction',
            name='referrer',
            field=models.ForeignKey(blank=True, help_text='Usuario dueño del código de referido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, max_length=6, null=True, unique=True),
        ),
    ]
